### ISSUE TITLE
Немного по коду пройдусь

### ISSUE THREAD

**Issue by bukaninandrei** [yamshchikov/rss-atom-converter#1]
https://github.com/yamshchikov/rss-atom-converter/blob/4f02950a53ef5d2e47afd4d545ddbadcb80e7eaa/lib/app.rb#L1

**Comment by ayamschikov** [comment]
Что с этим не так?

**Comment by bukaninandrei** [comment]
https://github.com/yamshchikov/rss-atom-converter/blob/4f02950a53ef5d2e47afd4d545ddbadcb80e7eaa/lib/app.rb#L7

```
можно использовать .fetch(:key, [])
```

это альтернатива

**Comment by bukaninandrei** [comment]
https://github.com/yamshchikov/rss-atom-converter/blob/4f02950a53ef5d2e47afd4d545ddbadcb80e7eaa/lib/app.rb#L16

в ruby 2.5.1 есть метод slice. Думаю, код можно сократить до
```
.new(opts.slice(''key1', 'key2'))
```

**Comment by ayamschikov** [comment]
Тут смысл не в сокращении, а чтобы понятно было, какие опции мы передаем. Самодокументирующийся код и все такое

**Comment by bukaninandrei** [comment]
В принципе, ничего плохого в этом нет, просто на мой вкус, если есть дубляж - нафиг его
